govuk-one-login/ipvreturn-api

- .github/workflows/post-merge-waf-build.yml
- .github/workflows/post-merge-waf-dev.yml
- .github/workflows/pull-request-WAF.yml
- .pre-commit-config.yaml
- .secrets.baseline
- infra-l2-waf/README.md
- infra-l2-waf/jest.config.ts
- infra-l2-waf/package-lock.json
- infra-l2-waf/package.json
- infra-l2-waf/template.yaml
- infra-l2-waf/tests/waf.test.ts
Add WAF Github actions workflows for DEV and BUILD
Add WAF template
[F2F-379](https://govukverify.atlassian.net/browse/F2F-379)
[F2F-379]: https://govukverify.atlassian.net/browse/F2F-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-379: Added WAF resource and associated files for IPV Return 

- .github/workflows/post-merge-dynamo-to-build.yml
- .github/workflows/post-merge-dynamo-to-dev.yml
- .github/workflows/pull-request-Dynamo.yml
- infra-l2-dynamo/.gitignore
- infra-l2-dynamo/jest.config.ts
- infra-l2-dynamo/package-lock.json
- infra-l2-dynamo/package.json
- infra-l2-dynamo/src/tests/infra/infra.test.ts
- infra-l2-dynamo/template.yaml
- infra-l2-dynamo/tsconfig.json
Added infra-l2-dynamo folder with package.json files and template file, as well as workflow file
> F2F-375: Added dynamodb template as well as workflow files

- .github/CODEOWNERS
- .github/pull_request_template.md
Added pr template and codeowners file
> F2F-445: Added pull request template file and codeowners file

- .github/workflows/post-merge-kms-build.yml
- .github/workflows/post-merge-kms-dev.yml
- .github/workflows/pull-request-KMS.yml
- infra-l2-kms/.gitignore
- infra-l2-kms/jest.config.ts
- infra-l2-kms/package-lock.json
- infra-l2-kms/package.json
- infra-l2-kms/src/tests/infra/infra.test.ts
- infra-l2-kms/template.yaml
- infra-l2-kms/tsconfig.json
IPV Return requires a KMS signing key
- Added the KMS key template
- Associated workflow files
- [F2F-377](https://govukverify.atlassian.net/browse/F2F-377)
[F2F-377]: https://govukverify.atlassian.net/browse/F2F-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-377: Added KMS signing key

- .github/pull_request_template.md
- .github/workflows/post-merge-package-to-build.yml
- .github/workflows/post-merge-package-to-dev.yml
- .github/workflows/pull-request.yml
- src/.eslintrc.js
- src/services/SendEmailService.ts
- src/tests/infra/template.test.ts
- src/tests/unit/GovNotifyHandler.test.ts
- src/tests/unit/services/SendEmailService.test.ts
- src/utils/Response.ts
- src/utils/ValidationHelper.ts
Adding Github actions for Pull request, Deploy to Dev and Deploy to Build on merge
To enable pipeline checks to be run and deploy the artefacts to all the envs
- [F2F-543](https://govukverify.atlassian.net/browse/F2F-543)
[F2F-543]: https://govukverify.atlassian.net/browse/F2F-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-543]: Adding pull request and deploy GHAs for Return

- deploy/template.yaml
Update the log level for troubleshooting the pipeline issue
> [F2F-391]-Changing the log level to debug to troubleshoot the pipeline issue

- src/package-lock.json
- src/services/PostEventProcessor.ts
- src/tests/unit/services/PostEventProcessor.test.ts
Added logic to the postEvent lambda such that:
it does not process AUTH_IPV_AUTHORISATION_REQUESTED events where component_id = “UNKNOWN” and this event is NOT saved in the DB
https://govukverify.atlassian.net/browse/F2F-674
> [F2F-674] Check component_id is not UNKNOWN for AUTH_IPV_AUTHORISATION_REQUESTED event

- deploy/template.yaml
- src/tests/infra/template.test.ts
Added a MethodSettings block to the Serverless::Api definition
- [F2F-719](https://govukverify.atlassian.net/browse/F2F-719)
[F2F-719]: https://govukverify.atlassian.net/browse/F2F-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added MethodSettings to REST APIGW definition

- deploy/template.yaml
- src/services/EnvironmentVariables.ts
- src/services/SessionProcessor.ts
Platform team have added the required permissions to create the OIDCProvider, so reverting back the code change to reintroduce the AssumeRoleWithWebIdentity code in the application.
> [F2F-716]-Revert changes and reintroduce AssumeRoleWithWebIdentity

- src/PostEventHandler.ts
- src/models/ReturnSQSEvent.ts
- src/models/SessionEvent.ts
- src/models/SessionReturnRecord.ts
- src/services/IPRService.ts
- src/services/PostEventProcessor.ts
- src/services/SessionEventProcessor.ts
- src/tests/unit/data/dynamodb-stream-record.ts
- src/tests/unit/services/PostEventProcessor.test.ts
- src/tests/unit/services/SessionEventProcessor.test.ts
- src/tests/unit/services/SessionProcessor.test.ts
- src/tests/unit/utils/PersonIdentityUtils.test.ts
- src/utils/PersonalIdentityUtils.ts
As agreed [here](https://gds.slack.com/archives/C04N9K8GZDX/p1685821801352049?thread_ts=1685707211.898849&cid=C04N9K8GZDX) `nameParts` are now going to be sent in the `IPV_F2F_CRI_VC_CONSUMED` event. Proposed changes as detailed in the ticket include the update of `PostEventProcessor`  and `SessionEventProcessor` to handle the `nameParts` and include them in the call to govNotify.
Event structure to be is 
```
{
"event_name": "IPV_F2F_CRI_VC_CONSUMED",
"component_id": "https://g1vp8kzas9.execute-api.eu-west-2.amazonaws.com",
"user": {
"user_id": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
"session_id": null,
"govuk_signin_journey_id": "unknown",
"ip_address": null
},
"restricted": {
"nameParts": [
{
"type": "GivenName",
"value": "ANGELA"
},
{
"type": "GivenName",
"value": "ZOE"
},
{ …
```
> [F2F-734] Updates to reflect IPV_F2F_CRI_VC_CONSUMED event sending nameParts

- deploy/template.yaml
- src/SessionHandler.ts
- src/services/SessionProcessor.ts
- src/tests/unit/services/SessionProcessor.test.ts
Removing the PII data from Session lambda logs.
- [F2F-856](https://govukverify.atlassian.net/browse/F2F-856)
[F2F-856]: https://govukverify.atlassian.net/browse/F2F-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-856] IPR | Logging | Remove all PII from /getSessionEventData logs

- src/services/IPRService.ts
https://govukverify.atlassian.net/browse/F2F-672
> F2F-672 Add expired session check

- deploy/template.yaml
Created the following cloud watch alarms for the IPV return backend
5XXErrorAlarm
5XXErrorCriticalAlarm
Session5XXApiGwErrorAlarm
Session5XXApiGwErrorCriticalAlarm
Session4XXApiGwErrorAlarm
LatencyAlarm
TXMASQSOldMessagesAlarm
TXMADLQMessagesVisibleAlarm
GovNotifySQSOldMessagesAlarm
GovNotifyDLQMessagesVisibleAlarm
LambdaTimeoutAlarm
ConcurrencyAlarmDashboard
ThrottlesAlarmDashboard:
CriticalAlarmDashboard:
WarningAlarmDashboard:
- [F2F-465](https://govukverify.atlassian.net/browse/F2F-465)
[F2F-465]: https://govukverify.atlassian.net/browse/F2F-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-465: Implement Monitoring & Alerts for IPV Return backend

- .github/workflows/post-merge-dynamo-to-build.yml
- .github/workflows/post-merge-dynamo-to-dev.yml
- .github/workflows/post-merge-kms-build.yml
- .github/workflows/post-merge-kms-dev.yml
- .github/workflows/post-merge-package-to-build.yml
- .github/workflows/post-merge-package-to-dev.yml
- .github/workflows/post-merge-waf-build.yml
- .github/workflows/post-merge-waf-dev.yml
- .github/workflows/pull-request-Dynamo.yml
- .github/workflows/pull-request-KMS.yml
- .github/workflows/pull-request-WAF.yml
- .github/workflows/pull-request.yml
GHA pipeline step aws-actions/setup-sam@v2 failing as below:
dding change as suggested [here](https://gds.slack.com/archives/C02R5AB0VV0/p1689611069795149)
> [IPR]: To resolve aws-actions/setup-sam@v2 breaking

- src/tests/api/govNotifySqs.test.ts
- src/tests/api/utils/ApiTestSteps.ts
- src/tests/data/sqs-events.ts
Tests update and working for IRVR api
schema for event updated with the correct fields
- [F2F-871](https://govukverify.atlassian.net/browse/F2F-871)
[F2F-871]: https://govukverify.atlassian.net/browse/F2F-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-871]: https://govukverify.atlassian.net/browse/F2F-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-871 qa

- .github/workflows/post-merge-gov-notify-stub-to-dev.yml
> Fix for Dev pipeline

- .github/workflows/post-merge-gov-notify-stub-to-dev.yml
- gov-notify-stub/template.yaml
> [F2F-583] fixing pipeline

- .github/workflows/post-merge-gov-notify-stub-to-dev.yml
- gov-notify-stub/template.yaml
Updating the MockGovNotifyRestApiUsagePlan to include the DependsOn clause.
> [F2F-583] Updating the MockGovNotifyRestApiUsagePlan

- deploy/template.yaml
- run-tests.sh
Adding env variables to run-test.sh and template.yml to support pipeline execution
Tests failing in CodeBuild pipeline 
N/A
> add env variables needed for govnotify test

- src/tests/unit/services/SessionEventProcessor.test.ts
- src/utils/ValidationHelper.ts
Log updates
Improving prod debugging.
- [KIWI-1310](https://govukverify.atlassian.net/browse/KIWI-1310)
[KIWI-1310]: https://govukverify.atlassian.net/browse/KIWI-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1310] Improving IPR logs for ValidationHelper

- src/tests/api/postEventStream.test.ts
Increase timeout for postStreamEvent tests 
Pipeline tests failing in build deploy due to timeout errors 
N/A
> Increase timeout for postStreamEvent tests

- deploy/template.yaml
- src/models/Email.ts
- src/services/IPRService.ts
- src/services/SendEmailProcessor.ts
- src/services/SendEmailService.ts
- src/tests/unit/services/IPRService.test.ts
- src/tests/unit/services/SendEmailProcessor.test.ts
- src/tests/unit/services/SendEmailService.test.ts
Reverts govuk-one-login/ipvreturn-api#95
> Revert "Remove static email name validations"

- deploy/template.yaml
- src/GovNotifyHandler.ts
- src/services/IPRService.ts
- src/services/SendEmailProcessor.ts
- src/services/SendEmailService.ts
- src/tests/unit/services/SendEmailProcessor.test.ts
- src/utils/ValidationHelper.ts
Refactors GovNotify within IPR
> [KIWI-1369] - Refactor GovNotify Handler

- src/PostEventHandler.ts
- src/services/IPRService.ts
- src/services/PostEventProcessor.ts
- src/tests/unit/PostEventHandler.test.ts
- src/tests/unit/services/PostEventProcessor.test.ts
- src/utils/Constants.ts
Refactors PostEventHandler within IPR
> [KIWI-1367] - Refactor PostEventHandler

- src/PostEventHandler.ts
- src/services/IPRService.ts
- src/services/PostEventProcessor.ts
- src/tests/unit/PostEventHandler.test.ts
- src/tests/unit/services/PostEventProcessor.test.ts
- src/utils/Constants.ts
This reverts commit 8801d74313e1e9bbe72f195a6802e5b8d3dfa647.
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> Revert "[KIWI-1367] - Refactor PostEventHandler (#101)"

- deploy/template.yaml
Address misconfiguration with the monitoring in IPR
Added log metric filters and alarms for IPR
- [KIWI-1225](https://govukverify.atlassian.net/browse/KIWI-1225)
[KIWI-1225]: https://govukverify.atlassian.net/browse/KIWI-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1225] Correct Monitoring Misconfiguration for IPR

- src/models/ReturnSQSEvent.ts
- src/models/SessionReturnRecord.ts
- src/tests/data/sqs-events.ts
Update IPR logic to fetch documentType correctly from the updated TxMA F2F_DOCUMENT_UPLOADED Event https://github.com/govuk-one-login/txma-event-self-serve/pull/342
> Fix for updated F2F_YOTI_START event

- src/services/EnvironmentVariables.ts
- src/services/SessionProcessor.ts
Update expiry on OIDC token
Potential fix for https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?q=search%20index%3D%22gds_di_production%22%20(function_name%3D*ipvreturn-api)%20level%3DERROR%20%20message%3D%22getSessionBySub%20-%20failed%20executing%20get%20from%20dynamodb%22&earliest=-15m&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&sid=1706791924.2221010
> Update expiry on OIDC token

- .github/workflows/post-merge-dynamo-to-build.yml
- .github/workflows/post-merge-dynamo-to-dev.yml
- .github/workflows/post-merge-kms-build.yml
- .github/workflows/post-merge-kms-dev.yml
- .github/workflows/post-merge-package-to-build.yml
- .github/workflows/post-merge-package-to-dev.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- README.md
- Added pre-commit workflow
- Updated pre-commit hooks
- Updated readme
- Align with other repos across identity pod
- General housekeeping
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-486: Add pre-commit

- deploy/template.yaml
Added conditional logic to `POWERTOOLS_LOG_LEVEL` dependent on environment.
- [KIWI-1599](https://govukverify.atlassian.net/browse/KIWI-1599)
[KIWI-1599]: https://govukverify.atlassian.net/browse/KIWI-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1599] - IPR | BE | Limit logs in prod to INFO and higher

- run-tests-locally.sh
- run-tests.sh
Update run-tests logic to output report for failed test runs
Store report for failed runs in CodeBuild
- [KIWI-1685](https://govukverify.atlassian.net/browse/KIWI-1685)
[KIWI-1685]: https://govukverify.atlassian.net/browse/KIWI-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1685 QA IPR

- deploy/template.yaml
- Fix missing IsNotDevelopment condition
- Deployment failed due to the missing IsNotDevelopment condition
- [KIWI-1719](https://govukverify.atlassian.net/browse/KIWI-1719)
[KIWI-1719]: https://govukverify.atlassian.net/browse/KIWI-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1719: Fix the condition isNotDevelopment

- infra-l2-dynamo/README.md
- infra-l2-dynamo/src/tests/infra/infra.test.ts
- infra-l2-dynamo/template.yaml
Create new auth events table needed for performance improvements
- [KIWI-1756](https://govukverify.atlassian.net/browse/KIWI-1756)
[KIWI-1756]: https://govukverify.atlassian.net/browse/KIWI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1756: Create new auth events DDB table

- src/services/PostEventProcessor.ts
- src/tests/unit/services/PostEventProcessor.test.ts
Reverts govuk-one-login/ipvreturn-api#186
> Revert "[KIWI-1756]- IPR | BE | Improve performance with Auth events table"

- deploy/template.yaml
Due to the change introduced in KIWI-552, the domainName was updated in production causing the user redirection issue.
Fixing Prod issue.
> [KIWI-552]Fixes the issue re domainName change in production.

- .github/workflows/post-merge-dynamo-to-build.yml
- .github/workflows/post-merge-dynamo-to-dev.yml
- .github/workflows/post-merge-gov-notify-stub-to-build.yml
- .github/workflows/post-merge-gov-notify-stub-to-dev.yml
- .github/workflows/post-merge-kms-build.yml
- .github/workflows/post-merge-kms-dev.yml
- .github/workflows/post-merge-oidc-stub-to-dev.yml
- .github/workflows/post-merge-package-to-build.yml
- .github/workflows/post-merge-package-to-dev.yml
- .github/workflows/post-merge-test-harness-package-to-build.yml
- .github/workflows/post-merge-test-harness-package-to-dev.yml
- Update upload action version v3 to v3.8.1
- Update the sam build template path
- Update upload action version v3 to v3.8.1 and add the full sam build path
- [IPS-838](https://govukverify.atlassian.net/browse/IPS-838)
[IPS-838]: https://govukverify.atlassian.net/browse/IPS-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-838: Update upload action version

- gov-notify-stub/src/package.json
- infra-l2-dynamo/.gitignore
- infra-l2-dynamo/package-lock.json
- infra-l2-dynamo/package.json
- infra-l2-dynamo/src/tests/infra/infra.test.ts
- infra-l2-kms/.gitignore
- infra-l2-kms/package-lock.json
- infra-l2-kms/package.json
- infra-l2-kms/src/tests/infra/infra.test.ts
- oidc-stub/src/package.json
- src/package-lock.json
- src/package.json
- src/tests/infra/template.test.ts
Migrate from AWS CDK v1 to AWS CDK v2
To address vulnerabilities
> IPR | BE | Migrate from AWS CDK v1 to AWS CDK v2

- gov-notify-stub/template.yaml
Remove MockGovNotifyRestApiUsagePlan
> Fix Notify Pipeline

- gov-notify-stub/template.yaml
Reverts govuk-one-login/ipvreturn-api#223
> Revert "Fix Notify Pipeline"

- gov-notify-stub/src/package-lock.json
- oidc-stub/src/package-lock.json
- src/package-lock.json
> [KIWI-XXXX] - Updates package-lock files

- deploy/template.yaml
- deploy role
- deploy role is required
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> IPS-1096 updated deployment pref

- deploy/template.yaml
Toggled redrive functionality on
> KIWI-2354: Toggled on redrive
