govuk-one-login/ipvreturn-api

.github/workflows/pull-request-sonar.yml, .github/workflows/sonar-analysis-on-merge.yml, infra-l2-dynamo/jest.config.ts, infra-l2-kms/jest.config.ts, sonar-project.properties, src/package.json
Implement sonar scan properties and workflow to run sonar scan on the di-ipvreturn-api.
This includes the scan files, exclusions and code coverage.   
- [F2F-530](https://govukverify.atlassian.net/browse/F2F-530)
[F2F-530]: https://govukverify.atlassian.net/browse/F2F-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-530: Add sonar scan to ipvreturn-api

deploy/template.yaml
Route the cloud watch logs to CSLS processing.  AWS Account id are configured on the CSLS.
Platform configuration is done for the ipvreturn-api.
Modified to allow all the environment to send logs. 
- [F2F-486](https://govukverify.atlassian.net/browse/F2F-486)
[F2F-486]: https://govukverify.atlassian.net/browse/F2F-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-486: Add the IPR to CSLS processing

deploy/template.yaml, src/services/EnvironmentVariables.ts, src/services/SessionProcessor.ts
Adding a config switch in the code to temporarily skip the AussumeRoleWithWebIdentiy and use GetItem directly to fetch the sessionEvent data.
After deploying these changes to backend-main-richa-1 BE stack the FE is now restored and able to redirect the user to the return journey url as expected. PFB the screenshot as evidence.
Please Note: Once the main stack is deployed successfully with these changes, we may have to update the FE stack to point to the BE main stack instead of backend-main-richa-1 stack.
=> [F2F-715]-getSessionEventLambda | Replacing AssumeRoleWithWebIdentity call and using GetItem directly

deploy/template.yaml
IPVreturn services offer service to produce and consume events. To consume events, provide necessary permissions to lambda function to access the TxMA SQS queue and receive event. 
Added policies to receive event from TxMA queue to allow post event function to receive message.
Subscribe TxMA SQS to receive message form the cross account queue
- [F2F-388](https://govukverify.atlassian.net/browse/F2F-388)
[F2F-388]: https://govukverify.atlassian.net/browse/F2F-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-388: Setup Infrastructure and permissions to consumer TxMA events

deploy/template.yaml
- Template was trying to fetch a TxMAKey in dev and build for which a mapping value didn't exist. Amended the existing conditional to avoid this error (the actual key value is not used in dev and build)
- added OIDCUrl for prod to mappings
- [F2F-388](https://govukverify.atlassian.net/browse/F2F-388)
- [F2F-726](https://govukverify.atlassian.net/browse/F2F-726)
[F2F-388]: https://govukverify.atlassian.net/browse/F2F-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-726]: https://govukverify.atlassian.net/browse/F2F-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-388: Fix for MockTxMASQS conditional Error

deploy/template.yaml
Removed permissions boundary from OIDC
- [F2F-726](https://govukverify.atlassian.net/browse/F2F-726)
[F2F-726]: https://govukverify.atlassian.net/browse/F2F-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-726: Removed permissions boundary from oidc

deploy/template.yaml
Currently SQS message retention period is set to default 4 days.
TxMA message queues need to have message retention of 7 days.
Added TxMA message retention period to 7 days without altering the existing queues
- [F2F-765](https://govukverify.atlassian.net/browse/F2F-765)
[F2F-765]: https://govukverify.atlassian.net/browse/F2F-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-765: Modify TxMA SQS Queue retention period to 7 days

src/services/PostEventProcessor.ts
Log messages in PostEventProcesssor have been update to more clearly show the issue that has occurred
We had two very similar logs that were not clear
- [F2F-819](https://govukverify.atlassian.net/browse/F2F-819)
[F2F-819]: https://govukverify.atlassian.net/browse/F2F-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-819] Updates logs to be more clear

src/jest.setup.ts, src/tests/unit/services/SendEmailService.test.ts
Added unit-tests in GovNotify to test the re-tries logic.
BAQAing this ticket required a way to test GovNotify retry logic incase we receive 500/429 errors
- [F2F-490](https://govukverify.atlassian.net/browse/F2F-490)
[F2F-490]: https://govukverify.atlassian.net/browse/F2F-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-490]Adding unit-tests for testing GovNotify re-try logic

.gitignore, Dockerfile, deploy/template.yaml, run-tests-locally.sh, run-tests.sh, src/.gitignore, src/README.md, src/jest.config.ts, src/models/ReturnSQSEvent.ts, src/package-lock.json, src/package.json, src/tests/api/postEventStream.test.ts, src/tests/api/utils/ApiTestSteps.ts, src/tests/data/sqs-events.ts, src/tests/unit/GovNotifyHandler.test.ts, src/tests/unit/PostEventHandler.test.ts, src/tests/unit/data/sqs-events.ts, src/tests/unit/services/PostEventProcessor.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/services/SendEmailService.test.ts
Add an API test harness which can be used to exercise a deployed instance of this code in AWS by injecting test events in to the mock TXMA consumer queue, and checking for the required state to be reached eventually in the DynamoDB table.
So to enable live / dynamic testing in pipeline on the route-to-live.
- [F2F-870](https://govukverify.atlassian.net/browse/F2F-870)
[F2F-870]: https://govukverify.atlassian.net/browse/F2F-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-870 API Test Harness

README.md, gov-notify-templates/ReturnJourneyEmail
Added a file with IPV Return gov notify email template with formatting.
We need a permanent location to store Gov notify template backups.
- [F2F-386](https://govukverify.atlassian.net/browse/F2F-386)
Return journey Email template in 
[F2F-359]: https://govukverify.atlassian.net/browse/F2F-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-386]: https://govukverify.atlassian.net/browse/F2F-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gov notify IPV return templates

deploy/template.yaml
Add the new template-id for the Gov notify email template from `GOV.UK One Login - Prove your identity at a Post Office `service
To use the Live service for sending emails
- [F2F-802](https://govukverify.atlassian.net/browse/F2F-802)
[F2F-802]: https://govukverify.atlassian.net/browse/F2F-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-802] Updated templateId to use Live one on Prod

src/services/PostEventProcessor.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/PostEventProcessor.test.ts
- Changes validation issues for `AUTH_IPV_AUTHORISATION_REQUESTED` event to be warning
- Updates tests to make them more manageable by using objects rather than JSON strings
We are getting 100s of validation log errors in IPVR that are causing a lot of noise and making it difficult to debug. This change means that we no longer throw errors that come from incorrect `AUTH_IPV_AUTHORISATION_REQUESTED` as we are assuming that they are not meant for us
Event missing email
- [F2F-1001](https://govukverify.atlassian.net/browse/F2F-1001)
[F2F-1001]: https://govukverify.atlassian.net/browse/F2F-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1001] Changes validation issues for AUTH_IPV_AUTHORISATION_REQUESTED event to be warning

README.md, deploy/template.yaml
- Set reserved concurrencies for all lambdas which are deployed in all non-DEV environments. 
- These are required in BUILD since this is the environment used in performance testing. 
- A parameter has been added to allow them to be set when manually deploying in DEV should this be needed, but this must not be default.
- A parameter has been added to set threshold for Lambda concurrency alarm
- [F2F-781](https://govukverify.atlassian.net/browse/F2F-781)
[F2F-781]: https://govukverify.atlassian.net/browse/F2F-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-781: Set Reserved concurrency for Lambdas in Prod

src/models/ReturnSQSEvent.ts, src/services/PostEventProcessor.ts, src/services/SendEmailProcessor.ts, src/services/SessionProcessor.ts
Logs `govuk_signin_journey_id` from events coming into PostEventProcessor 
To help debugging in the future
- [F2F-874](https://govukverify.atlassian.net/browse/F2F-874)
[F2F-874]: https://govukverify.atlassian.net/browse/F2F-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-874 Logs govuk_signin_journey_id in postEvent processor

src/StreamProcessorHandler.ts
Updated the logging level from ERROR to INFO for the StreamProcessor
It was ERROR before
- [F2F-996](https://govukverify.atlassian.net/browse/F2F-996)
[F2F-996]: https://govukverify.atlassian.net/browse/F2F-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-996] - StreamProcessor readyToResumeOn

deploy/template.yaml
- Added policy to access MockTxMASQSQueue
- Added encryption keys and DLQ for the MockTxMASQSQueue.
- Added conditional check to allow performance to access TxMASQSQueue on Build Environment
- Fix MockTxMASQSQueue export variables
- [F2F-1129](https://govukverify.atlassian.net/browse/F2F-1129)
[F2F-1129]: https://govukverify.atlassian.net/browse/F2F-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1129: Add Policy to Allow Injection of SQS Messages

.github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml
- This is a fix for the api pipeline failure due to the API test ECR failure
- With the test container enabled, there is no test image available on the ECR registry. 
- Created the workflow to build the test images and push into the ECR registery
- [F2F-1194](https://govukverify.atlassian.net/browse/F2F-1194)
[F2F-1194]: https://govukverify.atlassian.net/browse/F2F-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1194: API test container ECR Repository and Github Workflow

src/services/SessionEventProcessor.ts, src/tests/unit/services/SessionEventProcessor.test.ts
adds `govuk_signin_journey_id` to stream processor logs
To enable production debugging
- [F2F-1156](https://govukverify.atlassian.net/browse/F2F-1156)
[F2F-1156]: https://govukverify.atlassian.net/browse/F2F-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1156] adds govuk_signin_journey_id to stream processor logs

deploy/template.yaml
- Performance test had issues with MockTxMASQSQueue injected data. Any data injected was not consumed by the post event function and send to DLQ
- Fix the MockTxMAEncryption keys for the dev and build environment
- [F2F-1129](https://govukverify.atlassian.net/browse/F2F-1129)
=> F2F-1129: Fix PostEventFunction to consume event from MockTxMASQSQueue

src/models/ReturnSQSEvent.ts, src/models/SessionReturnRecord.ts, src/services/PostEventProcessor.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/PostEventProcessor.test.ts, src/utils/Constants.ts
Updating our session store with postoffice visit timing details that we receive from F2F_DOCUMENT_UPLOADED TXMA event.
Updating the session store with the PO address and documentType and documentExpiryDate fields by consuming these values from F2F_YOTI_START and IPV_F2F_CRI_VC_CONSUMED TXMA events.
Unit-tests added to test all cases.
Evidence (Both success and negative cases) attached to the ticket for reference.
Post go-live enhancement requirement
- [F2F-1061](https://govukverify.atlassian.net/browse/F2F-1061)
[F2F-1061]: https://govukverify.atlassian.net/browse/F2F-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1061]Update Post Event to store additional postoffice visit timing details from TXMA event

.gitignore, run-tests-locally.sh, run-tests.sh, src/tests/api/postEventStream.test.ts
Adds missing env vars to test scripts
Test script was failing to run
Before
After
- [F2F-1105](https://govukverify.atlassian.net/browse/F2F-1105)
=> [KIWI-1105] Adds missing env vars to test scripts

src/tests/api/postEventStream.test.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/PostEventProcessor.test.ts, test-harness/test-harness-spec.yaml
Adding F2F_DOCUMENT_UPLOADED TXMA event in test-harness
Fixing test pipeline deployment
- [KIWI-1063](https://govukverify.atlassian.net/browse/KIWI-1063)
[KIWI-1063]: https://govukverify.atlassian.net/browse/KIWI-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding the new TXMA event

deploy/template.yaml
adds IsMockedEnvironment condition to mock txma outputs
Mock txma queue is not used outside of mocked environments
- [KIWI-1105](https://govukverify.atlassian.net/browse/KIWI-1105)
[KIWI-1105]: https://govukverify.atlassian.net/browse/KIWI-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1105] adds IsMockedEnvironment condition to mock txma outputs

Dockerfile, run-tests.sh, src/package-lock.json, src/package.json, src/tests/api/utils/ApiTestSteps.ts, test-harness/test-harness-spec.yaml
Uses AWS credential-providers to get credentials in the pipeline so that our interceptor works with sigv4
Tested against test harness with enabled apigw policy 
Test pipeline step is successful 
https://eu-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/ipvreturn-api-pipeline-Pipeline-FSPG9ANPAQVQ/view?region=eu-west-2
- [KIWI-1105](https://govukverify.atlassian.net/browse/KIWI-1105)
[KIWI-1105]: https://govukverify.atlassian.net/browse/KIWI-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1105 credentials

.github/CODEOWNERS, .github/pull_request_template.md
- Add the CODEOWNERS for new govuk-one-login github IPR API
- Modified the urls pointing to alphagov github repository
- [KIWI-1322](https://govukverify.atlassian.net/browse/KIWI-1322)
[KIWI-1322]: https://govukverify.atlassian.net/browse/KIWI-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1322: Github migration - Post clean up for IPVReturn API

src/services/IPRService.ts, src/tests/unit/services/IPRService.test.ts
Removes logic to capture IPR Sessions that have expired
=> Capture expired IPR Sessions

infra-l2-dynamo/template.yaml
Remove DynamoDB TimeToLiveSpecification to allow for attribute name to be change in future PR: https://github.com/govuk-one-login/ipvreturn-api/pull/100
**Before**
**After**
=> [KIWI-1362] - Remove DynamoDB TimeToLiveSpecification

infra-l2-dynamo/template.yaml
Update DynamoDB TimeToLiveSpecification AttributeName to match the record after having deleted it in PR: https://github.com/govuk-one-login/ipvreturn-api/pull/98
**Before**
**Run Preview**
**After**
=> [KIWI-1362] Enable TTL and set Attribute name to expiresOn

src/services/IPRService.ts, src/services/SendEmailProcessor.ts, src/services/SessionProcessor.ts, src/tests/unit/services/IPRService.test.ts
Remove stacktrace from getSessionBySub method call 
Prod incident userIds being leaked into splunk
=> [KIWI-1386] - Remove stacktrace from error log when getSessionBySub

README.md, deploy/template.yaml
"Introduced CloudFormation condition **NotLocalTestStack** to enable or disable the deployment of resources based on the environment not being 'dev' and the AWS CloudFormation stack name not being 'ipvreturn-api'."
**Local Deploy**
**CodePipeline Deploy**
=> [KIWI-1203] - Create new NotLocalTestStack condition to allow multiple deployments of IPR BE Stack

src/services/IPRService.ts, src/services/PostEventProcessor.ts, src/tests/unit/services/IPRService.test.ts, src/tests/unit/services/PostEventProcessor.test.ts, src/utils/Constants.ts
Adds new method to obfuscate TxMA Events before logging them out in Splunk to diagnose reasons why in some scenarios we don't send the dynamic emails
=> [KIWI-1365] - Add new obfuscateJSONValues method and log out obfuscated TxMA Events

deploy/template.yaml
- Integrate Lambda functions to ingest metrics in dynatrace 
- Add dyntrace SSM parameters and inject lambda logs to dynatrace
- This will allow dynatrace to get lambda metric from the IPVReturn service
- [KIWI-1500](https://govukverify.atlassian.net/browse/KIWI-1500)
[KIWI-1500]: https://govukverify.atlassian.net/browse/KIWI-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1500:Enable Lambda metrics in Dynatrace

deploy/template.yaml
- Existing 4xx and 5xx alarms does not create invocations and errors.
- ApiName is configured wrong due to which invocations does not happen
- changed to get ApiId to configure the API gateway
- Configured the 5xx and 4xx errors alarms with ApiId
- ApiName configured incorrect causes a issue with getting invocations
- [KIWI-1497](https://govukverify.atlassian.net/browse/KIWI-1497)
[KIWI-1457]: https://govukverify.atlassian.net/browse/KIWI-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1497]: https://govukverify.atlassian.net/browse/KIWI-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1497: Fix 4xx and 5xx error alarms with ApiId

run-tests-locally.sh, src/models/ReturnSQSEvent.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/PostEventProcessor.test.ts
BE Stack: ipvreturn-api-1625
Test results: 
Add event_timestamp_ms to TxMA messages
- [KIWI-1625](https://govukverify.atlassian.net/browse/KIWI-1625)
[KIWI-1625]: https://govukverify.atlassian.net/browse/KIWI-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1625 QA Updates

run-tests-locally.sh, src/models/ReturnSQSEvent.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/IPRService.test.ts, src/tests/unit/services/PostEventProcessor.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/utils/Txma.test.ts, src/utils/TxmaEvent.ts
adds event_timestamp_ms to TXMA events
to provide more granularity
- [KIWI-1625](https://govukverify.atlassian.net/browse/KIWI-1625)
[KIWI-1625]: https://govukverify.atlassian.net/browse/KIWI-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1625: Add ms to txma events

deploy/template.yaml
Modify the support manual url pointing to the BE Metrics page. 
- Add Support Manual URL and point to the BE Metrics pages https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3626565651/IPR+BE+Metrics+Alerts
- Add Support manual description to Alarm descriptions
To include the support url on the alarms
- [KIWI-1668](https://govukverify.atlassian.net/browse/KIWI-1668)
[KIWI-1668]: https://govukverify.atlassian.net/browse/KIWI-1668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1669: Add Support Manual URL pointing to BE Metrics Page

deploy/template.yaml
Alarms are created on dev for every custom stack created on the dev account. 
In order to optimise the stack, alarm is set to off by default 
Change the flag to deploy on dev set to false.
Added the condition on metric filter and alarms
Modified the concurrency alarms flag.
Too many alarms created when a new custom is created.
- [KIWI-1719](https://govukverify.atlassian.net/browse/KIWI-1719)
- [IPS-678](https://govukverify.atlassian.net/browse/IPS-678)
[KIWI-1719]: https://govukverify.atlassian.net/browse/KIWI-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-678]: https://govukverify.atlassian.net/browse/IPS-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1719: Set Alarms to Off by Default in Dev

deploy/template.yaml
- Add missing Is notDevelopment condition
- IsnotDevelopment condition does not exist for setting the alarm on non-dev environments
- 
- [KIWI-1719](https://govukverify.atlassian.net/browse/KIWI-1719)
[KIWI-1719]: https://govukverify.atlassian.net/browse/KIWI-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1719: Set alarms to off default in dev

src/tests/api/postEventStream.test.ts, src/tests/api/utils/ApiTestSteps.ts
Add test to check SESSION_EVENTS_TABLE after F2F_YOTI_START Event
Send the following 2 events - VALID_AUTH_IPV_AUTHORISATION_REQUESTED_TXMA_EVENT, VALID_F2F_YOTI_START_WITH_PO_DOC_DETAILS_TXMA_EVENT
Validate the following sessionEvents dynamoDB fields: 
- clientName
- redirectUri
- userEmail
- documentType
- postOfficeInfo
Test changes to IPR BE to Improve performance with Auth events table
- [KIWI-1756](https://govukverify.atlassian.net/browse/KIWI-1756)
[KIWI-1756]: https://govukverify.atlassian.net/browse/KIWI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1756 - Check SESSION_EVENTS_TABLE after F2F_YOTI_START Event

src/services/PostEventProcessor.ts, src/tests/unit/services/PostEventProcessor.test.ts
Removed clientLandingPageCheck in PostEventProcessor
Check was preventing events after Auth Event being processed as RP value was empty
- [KIWI-1756](https://govukverify.atlassian.net/browse/KIWI-1756)
[KIWI-1756]: https://govukverify.atlassian.net/browse/KIWI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1756]- IPR | BE | Improve performance with Auth events table

deploy/template.yaml
Revert the OIDCURL to staging url until we have the OIDC stub deployed in dev
Unblocking the main BE stack testing by pointing the OIDC url back to staging until we have the OIDC stub deployed.
- [KIWI-552](https://govukverify.atlassian.net/browse/KIWI-552)
[KIWI-552]: https://govukverify.atlassian.net/browse/KIWI-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-552] Revert the OIDCURL to staging url until we have the OIDC stub deployed in dev

src/services/SendEmailService.ts, src/tests/unit/services/SendEmailService.test.ts
Log the id from the response body when an email is sent successfully
Enhancing the IPR GovNotify logs for Support engineer to grab the id to further investigate the email status using the id.
- [KIWI-1512](https://govukverify.atlassian.net/browse/KIWI-1512)
Evidence of the log for reference:
[KIWI-1512]: https://govukverify.atlassian.net/browse/KIWI-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1512]Updating logs to printout the response-id when an email is sent successfully.

.gitignore, deploy/template.yaml, src/jest.setup.ts, src/package.json, src/services/EnvironmentVariables.ts, src/services/IPRServiceSession.ts, src/services/SendEmailProcessor.ts, src/services/SessionProcessor.ts, src/tests/unit/SessionHandler.test.ts, src/tests/unit/services/IPRServiceAuth.test.ts, src/tests/unit/services/IPRServiceSession.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/services/SessionProcessor.test.ts, src/tests/unit/utils/Txma.test.ts, src/tsconfig.json, src/utils/TxmaEvent.ts
This change introduces the component_id field to all TxMA events. We've updated the EnvironmentVariables class to provide this ID, modified the TxmaEvent interface and buildCoreEventFields function to include it, and updated the SendEmailProcessor and SessionProcessor classes to use this new field. Corresponding test files have been updated to verify the presence of component_id in events. These changes improve event traceability and comply with new requirements for TxMA event structure.
1. EnvironmentVariables.ts:
- Added a new `componentId()` method to retrieve the COMPONENT_ID environment variable.
2. SendEmailProcessor.ts:
- Updated the `processRequest` method to include `component_id` in TxMA events.
- Modified the constructor to accept and store an EnvironmentVariables instance.
3. …
=> KIWI-1899: Added the issuer to relevant TxMA events and fixed test coverage

deploy/samconfig.toml, src/models/ReturnSQSEvent.ts, src/models/SessionEvent.ts, src/models/SessionReturnRecord.ts, src/services/IPRServiceSession.ts, src/services/PostEventProcessor.ts, src/tests/api/postEventStream.test.ts, src/tests/data/sqs-events.ts, src/tests/unit/services/IPRServiceSession.test.ts, src/tests/unit/services/PostEventProcessor.test.ts, src/utils/Constants.ts
Functionality added to "delete" a user's record in the session table if they choose to reset their VC from IPV core. This is the same as the existing code that runs after AUTH_DELETE_ACCOUNT event is consumed, but IPV_F2F_USER_CANCEL_END will come from a different place
To allow users to reset their pending VCs without fully deleting their account
- [KIWI-1967](https://govukverify.atlassian.net/browse/KIWI-1967)
[KIWI-1967]: https://govukverify.atlassian.net/browse/KIWI-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1967]- IPR | BE | Delete User Session Based on IPV_F2F_USER_CANCEL_END events

src/PostEventHandler.ts, src/services/PostEventProcessor.ts, src/tests/data/sqs-events.ts, src/tests/unit/PostEventHandler.test.ts, src/tests/unit/services/PostEventProcessor.test.ts
Error handling for IPV_F2F_USER_CANCEL_END event added - when Dynamo command to delete record fails, request retries 5 times then is put into DLQ. When the consumption of the event fails, a 500 is thrown and the message does not go to the DLQ
To correctly handle errors involving the new TxMA event 
- [KIWI-2055](https://govukverify.atlassian.net/browse/KIWI-2055)
[KIWI-2055]: https://govukverify.atlassian.net/browse/KIWI-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2055] - IPR | BE | Error Handling for cancelling F2F VCs

src/tests/api/postEventStream.test.ts
API test failing in main has been commented out until after the Christmas code freeze when further investigation can be made. Canary deployments were failing because of this failing test. Attached evidence to show that functionality of IPV_F2F_USER_CANCEL_END works but test is failing
=> [KIWI-1967-fix] - IPR | BE | Delete User Session Based on IPV_F2F_USER_CANCEL_END events

deploy/template.yaml
- updated deployment preference
- to fix the deployment in environment where canary is not enabled
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
=> IPS-1096 updated deployment pref

src/tests/api/postEventStream.test.ts
Re-Enable failed test in postEventStream.test.ts
Test ran locally and no issues identified - possible intermittent fail? 
- [KIWI-2121](https://govukverify.atlassian.net/browse/KIWI-2121)
[KIWI-2121]: https://govukverify.atlassian.net/browse/KIWI-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Re-enable Failing Stream Processor Test

.secrets.baseline, src/tests/api/utils/JwtUtils.test.ts
Adds unit tests for JwtUtils module
To increase code coverage and dependability of service
- [KIWI-2120](https://govukverify.atlassian.net/browse/KIWI-2120)
[KIWI-2120]: https://govukverify.atlassian.net/browse/KIWI-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2120] - Write unit tests for all methods of the JwtUtils class

deploy/template.yaml
Updated support links in alarm descriptions
To ensure users are taken to the relevant Confluence page if support is required
- [KIWI-2285](https://govukverify.atlassian.net/browse/KIWI-2285)
[KIWI-2285]: https://govukverify.atlassian.net/browse/KIWI-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2285] - Live Services | Incorrect support manual links in alarm descriptions

deploy/template.yaml
Added Firewall Manager (FMS) tags to template file
To accommodate a transition from COUNT (logging rule violations) to BLOCK (actively blocking rule violations) in the lower environments
- [KIWI-2479](https://govukverify.atlassian.net/browse/KIWI-2479)
[KIWI-2476]: https://govukverify.atlassian.net/browse/KIWI-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-2479]: https://govukverify.atlassian.net/browse/KIWI-2479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2479] - IPR | Add FMS tags for custom WAF policy migration in lower environments
